# Generated by Django 4.2.16 on 2025-04-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_addr', models.TextField()),
                ('Subject', models.TextField(null=True)),
                ('From', models.TextField(null=True)),
                ('To', models.JSONField(null=True)),
                ('extra_headers', models.JSONField(null=True)),
                ('mail_body', models.TextField(null=True)),
                ('attachments', models.JSONField(null=True)),
            ],
        ),
    ]
