# Generated by Django 4.2.16 on 2025-04-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='From',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='from_addr',
            field=models.EmailField(max_length=254),
        ),
    ]
