# Generated by Django 4.2.16 on 2025-04-30 08:43

from django.db import migrations, models
import mails.models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_alter_mail_from_alter_mail_from_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='To',
            field=models.JSONField(help_text='List of valid Email-Adresses', null=True, validators=[mails.models.JSONSchemaValidator({'items': {'format': 'email', 'max_length': 254, 'type': 'string'}, 'type': 'array'})]),
        ),
    ]
