# Generated by Django 4.2.16 on 2025-04-30 15:43

from django.db import migrations, models
import mails.models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_alter_mail_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='To',
            field=models.JSONField(default=[], help_text='List of valid Email-Adresses', validators=[mails.models.JSONSchemaValidator({'items': {'format': 'email', 'maxLength': 254, 'type': 'string'}, 'type': 'array'})]),
        ),
    ]
