# Generated by Django 4.2.16 on 2025-04-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='name',
            field=models.TextField(default='Django Reinhardt'),
            preserve_default=False,
        ),
    ]
