# Generated by Django 4.2.16 on 2025-04-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
