# Generated by Django 4.2.16 on 2025-04-11 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_artist_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug_id',
            field=models.CharField(default='', max_length=32, unique=True, validators=[django.core.validators.RegexValidator('[a-z_]{0,23}-[0-9a-f]{8}')]),
            preserve_default=False,
        ),
    ]
