# Generated by Django 4.2.16 on 2025-04-25 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_artist_slug_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug_id',
            field=models.CharField(help_text='A (possibly empty) name in lower case asci alphabet letters or underscores [a-z_] followed by an 8 digit lowercase hex number. (e.g.: "the_the-e461ca37")', max_length=32, unique=True, validators=[django.core.validators.RegexValidator('[a-z_]{0,23}-[0-9a-f]{8}')]),
        ),
    ]
